### ISSUE TITLE
When I add the variable of TaskControl and then deploy the veristand project to localhost, some errors are reported

### ISSUE THREAD

**Issue by shenxiaochengd** [NIVeriStandAdd-Ons/Hexagon-VTD-Custom-Device#1]
Thanks to this great CD for helping me realize the possibility of co-simulation of veristand and VTD, it was very smooth to build the source code into a CD and call it with veristand, but when I added the variable of TaskControl, and then deployed the veristand project to localhost, this error will be reported, If I do not add a data channel, I can deploy normallyplease give me some help, thanks.
![image](https://github.com/NIVeriStandAdd-Ons/Hexagon-VTD-Custom-Device/assets/40509972/7e1a0d2e-521d-4b8f-baad-98c410c1e9ee)

**Comment by tlemiere** [comment]
This error often is linked to DLL calls, and there are two of them that are used in this custom device to communicate with VTD. According to [this](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000kGXrSAM&l=fr-FR), it might be that the DLLs that are called are not of the correct bitness.
What version of VeriStand/LabVIEW are you using? Since a few versions ago custom devices have to be built using LV 64 bit only, but I'm not sure if the Windows DLLs are 32 or 64 bits. They probably are 32 bit only so that might be the problem

**Comment by shenxiaochengd** [comment]
I used the 2021 version of LabView and Veristand the day before yesterday, I retried the 2020 version of LabView and Veristand, and the above problem solved perfectly,thanks for the guidance.
